main/Route/BankAccount/routes.py
from flask import Blueprint, flash, redirect, render_template, url_for, abort
from flask_login import login_required, current_user

from main.DataLayer.Core.Bank_Services import Bank_Service

from ...DataLayer.Database.models import Bank
from ...Core.Db_Core import Public_Service
from main.DataLayer.Core.User_Services import User_Service

from main.Route.BankAccount.forms import Create_Bank_Account_Form, Increase_BalanceForm
from main.Route.BankAccount.tools import Bank_Tools

accounts = Blueprint('accounts', __name__)
bank_tools = Bank_Tools()
bank_service = Bank_Service()
user_service = User_Service()
Bank_Pu_Service = Public_Service(Bank)


@accounts.route('/create/bank_account', methods=['GET', 'POST'])
@accounts.route('/home/create/bank_account', methods=['GET', 'POST'])
@login_required
def Create_Bank_Account():
    form = Create_Bank_Account_Form()
    if form.validate_on_submit():
        if bank_tools.Build_Bank_Account(form):
            flash('Your Bank Account has been created successfully', 'success')
            return redirect(url_for('base.HomePage'))
        else:
            flash(
                'There was an error creating your Bank Account. Please try again later.', 'danger')
    return render_template('BankTemplate/Create_Bank_Account.html', form=form)


@accounts.route('/bank_account/<int:bank_id>/charge/balance', methods=['GET', 'POST'])
@accounts.route('/home/bank_account/<int:bank_id>/charge/balance', methods=['GET', 'POST'])
@login_required
def Increase_Balance(bank_id):
    bank_account = Bank_Pu_Service.Get_By_Id_Or_404(bank_id)

    if bank_account.user != current_user:
        abort(403)

    form = Increase_BalanceForm()
    if form.validate_on_submit():
        bank_account.balance = bank_account.balance + form.sallary.data
        Bank_Pu_Service.Save_Changes()
        flash('Your Bank Account With This {} Fullname and {} password includes this {}$ balance has been increased.'.format(
            bank_account.fullname, bank_account.password, bank_account.balance), 'success')
        return redirect(url_for('base.HomePage'))
    return render_template('BankTemplate/Increase_Balance.html', form=form, bank_account=bank_account)


@accounts.route('/continue/as', methods=['GET', 'POST'])
@login_required
def Continue_As():
    accounts = bank_service.Get_All_Bank_Accounts_By_User(current_user)
    return render_template('BankTemplate/Continue_As.html', accounts=accounts)

main/Route/BankStaticTransaction/routes.py

from flask import Blueprint, render_template, url_for, request, abort, flash, redirect
from flask_login import current_user, login_required

from main.DataLayer.Core.Static_Transaction_Services import Static_Transaction_Service
from main.Route.BankStaticTransaction.forms import Create_Static_Transaction_Form
from main.Route.BankStaticTransaction.tools import Static_Transaction_Tools
from main.Route.Users.tools import User_Tools
from ...DataLayer.Database.models import Bank, StaticTransaction

from ...Core.Db_Core import Public_Service

static = Blueprint('static', __name__)
Bank_Pu_Service = Public_Service(Bank)
static_pu_service = Public_Service(StaticTransaction)
static_service = Static_Transaction_Service()
static_tools = Static_Transaction_Tools()
user_tools = User_Tools()


@static.route('/user/bank/<int:bank_id>/transaction', methods=['GET', 'POST'])
@static.route('/home/user/bank/<int:bank_id>/transaction', methods=['GET', 'POST'])
@login_required
def Static_Transaction(bank_id):
    page = request.args.get('page', 1, type=int)
    bank_account = Bank_Pu_Service.Get_By_Id_Or_404(bank_id)

    if bank_account.user != current_user:
        abort(403)

    if user_tools.Is_Account_Active(bank_account.user):
        flash('Your Account Is Not Active', 'danger')
        return redirect(url_for('base.HomePage'))

    transactions = static_service.Get_Paginated_Transactions_By_Bank(page,
                                                                     bank_account)
    return render_template('StaticTransactionTemplate/Static_Transaction_List.html', transactions=transactions, bank_account=bank_account)


@static.route('/create_trans/<int:bank_id>', methods=['GET', 'POST'])
@static.route('/home/create_trans/<int:bank_id>', methods=['GET', 'POST'])
@login_required
def Create_Trans(bank_id):
    account = Bank_Pu_Service.Get_By_Id_Or_404(bank_id)

    if account.user != current_user:
        abort(403)

    if user_tools.Is_Account_Active(account.user):
        flash('Your Account Is Not Active', 'danger')
        return redirect(url_for('base.HomePage'))

    form = Create_Static_Transaction_Form()
    if form.validate_on_submit():
        static_tools.Do_Create_Static_Transaction(form, account)
        flash('transaction Submited ', 'success')
        return redirect(url_for('static.Static_Transaction', bank_id=bank_id))
    return render_template('StaticTransactionTemplate/Create_Static_Transaction.html', form=form)


@static.route('/update/trans/<int:trans_id>', methods=['GET', 'POST'])
@static.route('/home/update/trans/<int:trans_id>', methods=['GET', 'POST'])
@login_required
def Update_Trans(trans_id):
    transaction = static_pu_service.Get_By_Id_Or_404(trans_id)

    if transaction.bank.user != current_user:
        abort(403)

    if user_tools.Is_Account_Active(transaction.bank.user):
        flash('Your Account Is Not Active', 'danger')
        return redirect(url_for('base.HomePage'))

    form = Create_Static_Transaction_Form()
    if form.validate_on_submit():
        transaction.bank.balance = transaction.bank.balance - \
            form.changed_money.data
        transaction.remained_money = transaction.previous_balance - form.changed_money.data
        transaction.changed_money = form.changed_money.data
        transaction.reason = form.reason.data
        transaction.started_date = form.started_date.data
        transaction.bank.balance = transaction.remained_money
        static_pu_service.Save_Changes()
        flash('transaction Updated Successfully', 'success')
        return redirect(url_for('static.Static_Transaction', bank_id=transaction.bank.id))
    elif request.method == 'GET':
        form.changed_money.data = transaction.changed_money
        form.reason.data = transaction.reason
        form.started_date.data = transaction.started_date
    return render_template('StaticTransactionTemplate/Create_Static_Transaction.html', form=form)


@static.route('/delete/trans/<int:trans_id>', methods=['GET', 'POST'])
@static.route('/home/delete/trans/<int:trans_id>', methods=['GET', 'POST'])
@login_required
def Delete_Trans(trans_id):
    transaction = static_pu_service.Get_By_Id_Or_404(trans_id)

    if transaction.bank.user != current_user:
        abort(403)

    if user_tools.Is_Account_Active(transaction.bank.user):
        flash('Your Account Is Not Active', 'danger')
        return redirect(url_for('base.HomePage'))

    static_pu_service.Del_To(transaction)
    flash('Deleted !', 'success')
    return redirect(url_for('static.Static_Transaction', bank_id=transaction.bank.id))

main/templates/StaticTransactionTemplate/Create_Static_Transaction.html
{% extends 'layout.html' %}
{% block content %}

<div class="content-section">
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">
                Create Your Transaction
            </legend>

            <div class="form-group">
                {{ form.changed_money.label(class="form-label") }}
                {% if form.changed_money.errors %}
                {{ form.changed_money(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.changed_money.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.changed_money(class="form-control form-control-lg") }}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.started_date.label(class="form-label") }}
                {% if form.started_date.errors %}
                {{ form.started_date(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.started_date.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.started_date(class="form-control form-control-lg") }}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.reason.label(class="form-label") }}
                {% if form.reason.errors %}
                {{ form.reason(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.reason.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.reason(class="form-control form-control-lg") }}
                {% endif %}
            </div>

        </fieldset>

        <div class="form-group mt-3">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
</div>

{% endblock content %}

main/templates/StaticTransactionTemplate/Static_Transaction_List.html
{% extends 'layout.html' %} {% block content %}
<a href="{{ url_for('static.Create_Trans',bank_id=bank_account.id) }}" class="btn btn-secondary btn-sm">Create New
  Transaction</a>
<a href="{{ url_for('accounts.Increase_Balance',bank_id=bank_account.id) }}" class="btn btn-secondary btn-sm">Increase
  Your Bank Sallary</a>
<table class="table table-striped">
  <thead>
    <th>Fullname</th>
    <th>Current_Balance</th>
    <th>Spends</th>
    <th>Date Time Of Spending</th>
    <th>Date Time Of Creating This</th>
    <th>Reason</th>
    <th></th>
  </thead>
  <tbody>
    {% for item in transactions.items %}
    <tr>
      <td>{{ item.bank.fullname }}</td>
      <td>{{ item.remained_money }}$</td>
      <td>{{ item.changed_money }}$</td>
      <td>{{ item.started_date }}</td>
      <td>{{ item.created_date }}</td>
      <td>
        <!-- Here -->
        <div class="dropdown">
          <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            Reason
          </button>
          <ul class="dropdown-menu">
            <li>
              {{ item.reason }}
            </li>
          </ul>
        </div>
        <!-- Here -->
      </td>
      <td>
        <a href="{{ url_for('static.Update_Trans',trans_id=item.id) }}" class="btn btn-primary btn-sm">Edit</a>
        <a href="{{ url_for('static.Delete_Trans',trans_id=item.id) }}" class="btn btn-danger btn-sm">Omit</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% for page_num in transactions.iter_pages() %}
{% if page_num %}
<a href="{{ url_for('static.Static_Transaction',page=page_num,bank_id=bank_account.id) }}"
  class="btn btn-primary btn-sm">{{ page_num }}</a>
{% else %}
...
{% endif %}
{% endfor %}
{% endblock content %}