main/Route/BankAccount/routes.py
from flask import Blueprint, flash, redirect, render_template, url_for, abort
from flask_login import login_required, current_user

from main.DataLayer.Core.Bank_Services import Bank_Service

from ...DataLayer.Database.models import Bank
from ...Core.Db_Core import Public_Service
from main.DataLayer.Core.User_Services import User_Service

from main.Route.BankAccount.forms import Create_Bank_Account_Form, Increase_BalanceForm
from main.Route.BankAccount.tools import Bank_Tools

accounts = Blueprint('accounts', __name__)
bank_tools = Bank_Tools()
bank_service = Bank_Service()
user_service = User_Service()
Bank_Pu_Service = Public_Service(Bank)


@accounts.route('/create/bank_account', methods=['GET', 'POST'])
@accounts.route('/home/create/bank_account', methods=['GET', 'POST'])
@login_required
def Create_Bank_Account():
    form = Create_Bank_Account_Form()
    if form.validate_on_submit():
        if bank_tools.Build_Bank_Account(form):
            flash('Your Bank Account has been created successfully', 'success')
            return redirect(url_for('base.HomePage'))
        else:
            flash(
                'There was an error creating your Bank Account. Please try again later.', 'danger')
    return render_template('BankTemplate/Create_Bank_Account.html', form=form)


@accounts.route('/bank_account/<int:bank_id>/charge/balance', methods=['GET', 'POST'])
@accounts.route('/home/bank_account/<int:bank_id>/charge/balance', methods=['GET', 'POST'])
@login_required
def Increase_Balance(bank_id):
    bank_account = Bank_Pu_Service.Get_By_Id_Or_404(bank_id)

    if bank_account.user != current_user:
        abort(403)

    form = Increase_BalanceForm()
    if form.validate_on_submit():
        bank_account.balance = bank_account.balance + form.sallary.data
        Bank_Pu_Service.Save_Changes()
        flash('Your Bank Account With This {} Fullname and {} password includes this {}$ balance has been increased.'.format(
            bank_account.fullname, bank_account.password, bank_account.balance), 'success')
        return redirect(url_for('base.HomePage'))
    return render_template('BankTemplate/Increase_Balance.html', form=form, bank_account=bank_account)


@accounts.route('/continue/as', methods=['GET', 'POST'])
@login_required
def Continue_As():
    accounts = bank_service.Get_All_Bank_Accounts_By_User(current_user)
    return render_template('BankTemplate/Continue_As.html', accounts=accounts)

main/Route/Products/routes.py
from flask import Blueprint, flash, redirect, abort, render_template, request, url_for
from flask_login import current_user, login_required
from main.Core.Db_Core import Public_Service
from main.DataLayer.Core.Cilent_Services import Cilent_Service
from main.DataLayer.Database.models import CilentProduct, Product
from main.Route.Products.forms import Build_New_Product_Form
from main.Route.Products.tools import Product_Tools
from main.Route.Users.tools import User_Tools


products = Blueprint('products', __name__)
Db_Product = Public_Service(Product)
product_tools = Product_Tools()
cilent_service = Cilent_Service()
user_tools = User_Tools()


@products.route('/user/new_purchase/<int:product_id>', methods=['GET', 'POST'])
@products.route('/home/user/new_purchase/<int:product_id>', methods=['GET', 'POST'])
def Sign_New_Purchase(product_id):

    if not (current_user.is_authenticated):
        flash('You are not authenticated. Please login to purchase', 'warning')
        return redirect(url_for('base.HomePage'))

    current_product = Db_Product.Get_By_Id_Or_404(product_id)

    if user_tools.Is_Account_Active(current_product.product_owner):
        flash('Your Account Is Not Active', 'danger')
        return redirect(url_for('base.HomePage'))

    if product_tools.Sign_New_purchase(current_product, current_user):
        flash('Added Your Cart !', 'success')

    return redirect(url_for('base.HomePage'))


@products.route('/user/create_product', methods=['GET', 'POST'])
@products.route('/user/create_product', methods=['GET', 'POST'])
@login_required
def Sign_Product():

    if current_user.role == "USER":
        abort(403)

    form = Build_New_Product_Form()
    if form.validate_on_submit():
        if product_tools.Sign_New_Product(form):
            flash('Your new product has been created successfully', 'success')
            return redirect(url_for('base.HomePage'))
    return render_template('ProductTemplate/Sign_Product.html', form=form)


@products.route('/user/update_product/<int:product_id>', methods=['GET', 'POST'])
@products.route('/user/update_product/<int:product_id>', methods=['GET', 'POST'])
def Update_Product(product_id):

    if current_user.role == "USER":
        abort(403)

    product = Db_Product.Get_By_Id_Or_404(product_id)

    if product.product_owner != current_user:
        abort(403)

    if user_tools.Is_Account_Active(product.product_owner):
        flash('Your Account Is Not Active', 'danger')
        return redirect(url_for('base.HomePage'))

    form = Build_New_Product_Form()
    if form.validate_on_submit():
        product.product_name = form.product_name.data
        product.product_gender = form.product_gender.data
        product.product_price = form.product_price.data
        product.product_summary = form.product_summary.data
        Db_Product.Save_Changes()
        flash('Your Product has been Updated Seccessfully.', 'success')
        return redirect(url_for('base.HomePage'))
    elif request.method == 'GET':
        form.product_name.data = product.product_name
        form.product_gender.data = product.product_gender
        form.product_price.data = product.product_price
        form.product_summary.data = product.product_summary
    return render_template('ProductTemplate/Sign_Product.html', form=form)


@products.route('/user/Delete_Product/<int:product_id>', methods=['GET', 'POST'])
@products.route('/home/user/Delete_Product/<int:product_id>', methods=['GET', 'POST'])
def Delete_Product(product_id):

    if current_user.role == "USER":
        abort(403)

    product = Db_Product.Get_By_Id_Or_404(product_id)

    if product.product_owner != current_user:
        abort(403)

    if user_tools.Is_Account_Active(product.product_owner):
        flash('Your Account Is Not Active', 'danger')
        return redirect(url_for('base.HomePage'))

    Db_Product.Del_To(product)
    flash("Your Product Has been deleted.", 'success')
    return redirect(url_for('base.HomePage'))

main/Route/Users/routes.py
from flask import Blueprint, flash, redirect, abort, render_template, request, url_for
from flask_login import current_user, login_required, logout_user
from main.Core.Db_Core import Public_Service
from main.Core.Security import Email_Token_Security
from main.DataLayer.Core.User_Services import User_Service
from main.DataLayer.Database.models import Card, User
from main.Route.Users.forms import AccountForm, ChangePasswordForm, Confrim_Email_Form, SignInForm, SignUpForm
from main.Route.Users.tools import User_Tools
import redis

users = Blueprint('users', __name__)
user_tools = User_Tools()
user_service = User_Service()
Db = Public_Service(User)
Db_Card = Public_Service(Card)
Sec_Service = Email_Token_Security()


@users.route('/signin', methods=['GET', 'POST'])
@users.route('/home/signin', methods=['GET', 'POST'])
def SignIn():

    if current_user.is_authenticated:
        return redirect(url_for('base.HomePage'))

    form = SignInForm()
    if form.validate_on_submit():
        is_ok = user_tools.Login_User(form)
        if is_ok:
            flash('You Signed in successfully.', 'success')
            return redirect(url_for('base.HomePage'))
        if is_ok is False:
            flash('Your email or your password is incorrect !', 'danger')
    return render_template('UserTemplate/SignIn.html', form=form)


@users.route('/signup', methods=['GET', 'POST'])
@users.route('/home/signup', methods=['GET', 'POST'])
def SignUp():

    if current_user.is_authenticated:
        return redirect(url_for('base.HomePage'))

    form = SignUpForm()
    if form.validate_on_submit():
        user = user_tools.SignUp_User(form=form)
        if user:
            flash('Your Account Was Created Successfully !', 'success')
            return redirect(url_for('users.SignIn'))
        else:
            flash('There Was An Error During Signing Up !', 'danger')
    return render_template('UserTemplate/SignUp.html', form=form)


@users.route('/changepassword', methods=['GET', 'POST'])
@users.route('/home/changepassword', methods=['GET', 'POST'])
@login_required
def ChangePassword():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        if user_tools.Change_UserPassword(form):
            flash('Your Password Was Updated Successfully', 'success')
            return redirect(url_for('base.HomePage'))
        else:
            flash('Your password is not correct !', 'danger')
    return render_template('UserTemplate/ChangePassword.html', form=form)


@users.route('/account', methods=['GET', 'POST'])
@users.route('/home/account', methods=['GET', 'POST'])
@login_required
def Account():
    Cards = user_service.Get_BankCards_By_Current_User(current_user)
    return render_template('UserTemplate/Account.html', Cards=Cards)


@users.route('/account/card/<int:card_id>', methods=['GET', 'POST'])
@users.route('/home/account/card/<int:card_id>', methods=['GET', 'POST'])
@login_required
def Account_Card(card_id):

    card = Db_Card.Get_By_Id_Or_404(card_id)

    if current_user != card.bank_accounts.user:
        abort(403)
    Cards = user_service.Get_BankCards_By_Current_User(current_user)
    # I Did not understand what the fuck is going on here...
    return render_template('UserTemplate/AccountCard.html', card=card, Cards=Cards)
    # Puting This Cards Will Fix All The Errors


@users.route('/change/account', methods=['GET', 'POST'])
@users.route('/home/change/account', methods=['GET', 'POST'])
@login_required
def Change_Account_Info():
    form = AccountForm()
    if form.validate_on_submit():
        current_user.email = form.email.data
        current_user.username = form.username.data
        current_user.phone = "0{}".format(form.phone.data)
        current_user.bio = form.bio.data
        Db.Save_Changes()
        flash('Your account info has been saved.', 'success')
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.phone.data = current_user.phone
        form.bio.data = current_user.bio
    return render_template('UserTemplate/Change_Account_Info.html', form=form)


@users.route('/logout')
@users.route('/home/logout')
@login_required
def Logout():
    logout_user()
    return redirect(url_for('base.HomePage'))


@users.route('/active/email/<int:user_id>', methods=['GET', 'POST'])
@users.route('/home/active/email/<int:user_id>', methods=['GET', 'POST'])
@login_required
def Confrim_Email(user_id):
    # Getting User Or 404
    user = Db.Get_By_Id_Or_404(user_id)

    # Checking For Some DumbAss Works
    if user.user_is_active == 1:
        return redirect(url_for('base.HomePage'))
    # Saving In Redis For Have Only One Message For Send # After 2 Min It Will Be Sended Automaticly
    r = redis.Redis()
    is_sms = r.get('{}_SEND_SMS'.format(user.id))
    is_user = r.get(user.username)
    # Checking For Several Message Sending
    if is_sms != 'YES' and is_user == None and is_user != user.username:
        user_tools.Send_Sms(user)
        r.set(user.username, user.username)
        r.set('{}_SEND_SMS'.format(user.id), 'YES')
    form = Confrim_Email_Form()
    if form.validate_on_submit():
        # Checking Seceret Code For Activition
        if form.confrim_code.data == user.secret_code:
            user.user_is_active = 1
            user.secret_code = Sec_Service.Generate_Random_Secret_Key(
                40000, 60000)
            Db.Save_Changes()
            flash('Your Account Is Acctive Know', 'success')
            # Deleteing Stored Data From Redis
            r.delete('{}_SEND_SMS'.format(user.id))
            r.delete(user.username)
            return redirect(url_for('base.HomePage'))
        else:
            flash('Wronge Verify Code', 'danger')

    return render_template('UserTemplate/Confrim_Email.html', form=form, user=user)


@users.route('/Send/Sms/<int:user_id>')
def Send_SMS(user_id):
    user = Db.Get_By_Id_Or_404(user_id)
    if user.user_is_active == 1:
        return redirect(url_for('base.HomePage'))
    user.secret_code = Sec_Service.Generate_Random_Secret_Key(40000, 60000)
    Db.Save_Changes()
    if user_tools.Send_Sms(user) == False:
        flash('This Is Equal To Zero , Error In Merging The Number')
    flash('You Have 2 Mintues To Enter Your Code OtherWise The Code Will Expire !', 'info')
    return redirect(url_for('users.Confrim_Email', user_id=user_id))

main/templates/UserTemplate/Account.html
{% extends 'layout.html' %}{% block content %}

<section style="background-color: #eee">
  <div class="container py-5">
    <div class="row">
      <div class="col">
        <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
          <ol class="breadcrumb mb-0">
            {% if current_user.role=="SELLER" %}
            <li class="breadcrumb-item"><a href="{{ url_for('products.Sign_Product') }}">Share Your Product</a></li>
            {% endif %}
            <li class="breadcrumb-item"><a href="{{ url_for('transactions.Transaction_List') }}">Your Transactions Log</a></li>
            <li class="breadcrumb-item"><a href="{{ url_for('accounts.Continue_As') }}">Transaction Managing</a></li>
            <li class="breadcrumb-item active" aria-current="page">
              User Profile
            </li>
          </ol>
        </nav>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body text-center">
            <img
              src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp"
              alt="avatar"
              class="rounded-circle img-fluid"
              style="width: 150px"
            />
            <h5 class="my-3">{{ current_user.username }}</h5>
            <p class="text-muted mb-1">{{ current_user.bio }}</p>
            <p class="text-muted mb-4">Bay Area, San Francisco, CA</p>
            <div class="d-flex justify-content-center mb-2">
              <button type="button" class="btn btn-primary">Follow</button>
              <button type="button" class="btn btn-outline-primary ms-1">
                Message
              </button>
            </div>
          </div>
        </div>
        <div class="card mb-4 mb-lg-0">
          <div class="card-body p-0">
            <ul class="list-group list-group-flush rounded-3">
              {% block card %} {% endblock card %}
            </ul>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Full Name</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{ current_user.username }}</p>
              </div>
            </div>
            <hr />
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Email</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{ current_user.email }}</p>
              </div>
            </div>
            <hr />
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Role</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{ current_user.role }}</p>
              </div>
            </div>
            <hr />
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Mobile</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{ current_user.phone }}</p>
              </div>
            </div>
            <hr />
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Address</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">Bay Area, San Francisco, CA</p>
              </div>
            </div>
          </div>
        </div>
        <!-- Here -->
        <div class="dropdown">
          <button
            class="btn btn-secondary btn-sm dropdown-toggle"
            type="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Your Cards
          </button>
          <ul class="dropdown-menu">
            {% if Cards %}
            {% else %}
            <div class="alert alert-danger">
              You Don't Have Any Bank Account And Cards
            </div>
            {% endif %}
            {% for i in Cards %}
            <li>
              <a
                class="dropdown-item"
                href="{{ url_for('users.Account_Card',card_id=i.id) }}"
                >{{ i.fullname }} : {{ i.card_cvv2 }}</a
              >
            </li>
            {% endfor %}
          </ul>
        </div>
        <!-- Here -->
        <div class="row">
          <div class="col-md-6">
            <div class="card mb-4 mb-md-0">
              <div class="card-body">
                <p class="mb-4">
                  <span class="text-primary font-italic me-1">assigment</span>
                  Project Status
                </p>
                <p class="mb-1" style="font-size: 0.77rem">Web Design</p>
                <div class="progress rounded" style="height: 5px">
                  <div
                    class="progress-bar"
                    role="progressbar"
                    style="width: 80%"
                    aria-valuenow="80"
                    aria-valuemin="0"
                    aria-valuemax="100"
                  ></div>
                </div>
                <p class="mt-4 mb-1" style="font-size: 0.77rem">
                  Website Markup
                </p>
                <div class="progress rounded" style="height: 5px">
                  <div
                    class="progress-bar"
                    role="progressbar"
                    style="width: 72%"
                    aria-valuenow="72"
                    aria-valuemin="0"
                    aria-valuemax="100"
                  ></div>
                </div>
                <p class="mt-4 mb-1" style="font-size: 0.77rem">One Page</p>
                <div class="progress rounded" style="height: 5px">
                  <div
                    class="progress-bar"
                    role="progressbar"
                    style="width: 89%"
                    aria-valuenow="89"
                    aria-valuemin="0"
                    aria-valuemax="100"
                  ></div>
                </div>
                <p class="mt-4 mb-1" style="font-size: 0.77rem">
                  Mobile Template
                </p>
                <div class="progress rounded" style="height: 5px">
                  <div
                    class="progress-bar"
                    role="progressbar"
                    style="width: 55%"
                    aria-valuenow="55"
                    aria-valuemin="0"
                    aria-valuemax="100"
                  ></div>
                </div>
                <p class="mt-4 mb-1" style="font-size: 0.77rem">Backend API</p>
                <div class="progress rounded mb-2" style="height: 5px">
                  <div
                    class="progress-bar"
                    role="progressbar"
                    style="width: 66%"
                    aria-valuenow="66"
                    aria-valuemin="0"
                    aria-valuemax="100"
                  ></div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="card mb-4 mb-md-0">
              <div class="card-body">
                <p class="mb-4">
                  <span class="text-primary font-italic me-1">assigment</span>
                  Project Status
                </p>
                <p class="mb-1" style="font-size: 0.77rem">Web Design</p>
                <div class="progress rounded" style="height: 5px">
                  <div
                    class="progress-bar"
                    role="progressbar"
                    style="width: 80%"
                    aria-valuenow="80"
                    aria-valuemin="0"
                    aria-valuemax="100"
                  ></div>
                </div>
                <p class="mt-4 mb-1" style="font-size: 0.77rem">
                  Website Markup
                </p>
                <div class="progress rounded" style="height: 5px">
                  <div
                    class="progress-bar"
                    role="progressbar"
                    style="width: 72%"
                    aria-valuenow="72"
                    aria-valuemin="0"
                    aria-valuemax="100"
                  ></div>
                </div>
                <p class="mt-4 mb-1" style="font-size: 0.77rem">One Page</p>
                <div class="progress rounded" style="height: 5px">
                  <div
                    class="progress-bar"
                    role="progressbar"
                    style="width: 89%"
                    aria-valuenow="89"
                    aria-valuemin="0"
                    aria-valuemax="100"
                  ></div>
                </div>
                <p class="mt-4 mb-1" style="font-size: 0.77rem">
                  Mobile Template
                </p>
                <div class="progress rounded" style="height: 5px">
                  <div
                    class="progress-bar"
                    role="progressbar"
                    style="width: 55%"
                    aria-valuenow="55"
                    aria-valuemin="0"
                    aria-valuemax="100"
                  ></div>
                </div>
                <p class="mt-4 mb-1" style="font-size: 0.77rem">Backend API</p>
                <div class="progress rounded mb-2" style="height: 5px">
                  <div
                    class="progress-bar"
                    role="progressbar"
                    style="width: 66%"
                    aria-valuenow="66"
                    aria-valuemin="0"
                    aria-valuemax="100"
                  ></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<div class="content-section mt-5">
  <small class="text-muted">
    Change Your Account Info ?
    <a
      href="{{url_for('users.Change_Account_Info')}}"
      class="btn btn-primary btn-sm"
      >Change</a
    >
  </small>
</div>
<div class="content-section mt-5">
  <small class="text-muted">
    Have No Bank Account ?
    <a
      href="{{url_for('accounts.Create_Bank_Account')}}"
      class="btn btn-primary btn-sm"
      >Create A New One</a
    >
  </small>
</div>
{% endblock content %}

main/templates/UserTemplate/Change_Account_Info.html
{% extends "layout.html" %} {% block content %}

<section class="vh-100" style="background-color: #9de2ff">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-md-9 col-lg-7 col-xl-5">
        <div class="card" style="border-radius: 15px">
          <div class="card-body p-4">
            <div class="d-flex text-black">
              <div class="flex-shrink-0">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-profiles/avatar-1.webp"
                  alt="Generic placeholder image" class="img-fluid" style="width: 180px; border-radius: 10px" />
              </div>
              <div class="flex-grow-1 ms-3">
                <h5 class="mb-1">{{ current_user.username }}</h5>
                <p class="mb-2 pb-1" style="color: #2b2a2a">
                  {{current_user.email}}
                </p>
                <div class="d-flex justify-content-start rounded-3 p-2 mb-2" style="background-color: #efefef">
                  <div>
                    <p class="small text-muted mb-1">Phone</p>
                    <p class="mb-0">{{current_user.phone}}</p>
                  </div>
                  <div class="px-3">
                    <p class="small text-muted mb-1">Bio</p>
                    <p class="mb-0">{{ current_user.bio }}</p>
                  </div>
                  <div>
                    <p class="small text-muted mb-1">Rating</p>
                    <p class="mb-0">8.5</p>
                  </div>
                </div>
                <div class="d-flex pt-1">
                  <button type="button" class="btn btn-outline-primary me-1 flex-grow-1">
                    Chat
                  </button>
                  <button type="button" class="btn btn-primary flex-grow-1">
                    Follow
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<div class="content-section">
  <form action="" method="post">
    {{ form.hidden_tag() }}

    <div class="form-outline mb-4">
      {{ form.username.label(class="form-label") }} {% if form.username.errors
      %} {{ form.username(class="form-control form-control-lg is-invalid") }}
      <div class="invalid-feedback">
        {% for error in form.username.errors %}
        <span>{{error}}</span>
        {% endfor %}
      </div>
      {% else %} {{ form.username(class="form-control form-control-lg") }} {%
      endif %}
    </div>

    <div class="form-outline mb-4">
      {{ form.email.label(class="form-label") }} {% if form.email.errors %} {{
      form.email(class="form-control form-control-lg is-invalid") }}
      <div class="invalid-feedback">
        {% for error in form.email.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
      {% else %} {{ form.email(class="form-control form-control-lg") }} {% endif
      %}
    </div>

    <div class="form-outline mb-4">
      {{ form.phone.label(class="form-label") }} {% if form.phone.errors
      %} {{ form.phone(class="form-control form-control-lg is-invalid") }}
      <div class="invalid-feedback">
        {% for error in form.phone.errors %}
        <span>{{error}}</span>
        {% endfor %}
      </div>
      {% else %} {{ form.phone(class="form-control form-control-lg") }} {%
      endif %}
    </div>

    <div class="form-outline mb-4">
      {{ form.bio.label(class="form-label") }} {% if form.bio.errors
      %} {{ form.bio(class="form-control form-control-lg is-invalid") }}
      <div class="invalid-feedback">
        {% for error in form.bio.errors %}
        <span>{{error}}</span>
        {% endfor %}
      </div>
      {% else %} {{ form.bio(class="form-control form-control-lg") }} {%
      endif %}
    </div>

    <div class="form-outline mb-4 mt-3">
      {{ form.submit(class="btn btn-primary") }}
    </div>
  </form>
</div>

<div class="content-section">
  <small class="text-muted">
    Change Your Password ?
    <a href="{{url_for('users.ChangePassword')}}" class="btn btn-primary btn-sm">Change</a> </small><br /><br />

  <small class="text-muted">
    Forgot Password ?
    <a href="#" class="btn btn-primary btn-sm">Reset Your Password</a>
  </small>
</div>
{% if current_user.user_is_active!=1 %}
<div class="border-top pt-3 mt-3">
  <small class="text-muted">
    Active Your Account ? <a href="{{url_for('users.Confrim_Email',user_id=current_user.id)}}"
      class="btn btn-secondary btn-sm">Active</a>
  </small>
</div>
{% endif %}
{% endblock %}

main/templates/UserTemplate/Confrim_Email.html
{% extends 'layout.html' %}
{% block content %}

<div class="alert alert-info">
    An Sms Including Active Code Have Been Sent For You ! Please Check Your Phone And Continue
</div>

<div class="content-section">
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">
                Confrim Your Email for : {{user.email}} and {{user.phone}}
            </legend>
            <div class="form-group">
                {{ form.confrim_code.label(class="form-label") }}
                {% if form.confrim_code.errors %}
                {{ form.confrim_code(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.confrim_code.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.confrim_code(class="form-control form-control-lg") }}
                {% endif %}
            </div>

        </fieldset>

        <div class="form-group mt-3">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
</div>

<p class="text-danger lead">You Have Only 2ms To Submit Your Active Code.</p>
<span class="text-muted" id="timer">120s</span>
<progress class="progress-bar bg-warning" id="progressBar" max="120" value="120">
    Progress
</progress>
<script type="text/javascript">
    const timerElement = document.getElementById("timer");
    const progressBar = document.getElementById("progressBar");

    let timerCounter = progressBar.max;

    const interval = setInterval(() => {
        if (timerCounter <= 1) {
            window.location.href = "{{ url_for('users.Send_SMS',user_id=current_user.id) }}"
            clearInterval(interval);
        }


        timerCounter = timerCounter - 1;
        timerElement.innerText = timerCounter + "s";
        progressBar.value = timerCounter;
    }, 1000);


</script>


<div class="border-top pt-3 mt-3">
    <small class="text-muted">
        return Back The Home ? <a href="{{url_for('base.HomePage')}}" class="btn btn-secondary btn-sm">Home Page</a>
    </small>
</div>


{% endblock content %}