main/Route/BankCard/routes.py
from flask import Blueprint, flash, redirect, abort, render_template, request, url_for
from flask_login import current_user, login_required
from main.Core.Db_Core import Public_Service
from main.DataLayer.Core.Bank_Services import Bank_Service
from main.DataLayer.Core.Cilent_Services import Cilent_Service
from main.DataLayer.Core.User_Services import User_Service
from main.DataLayer.Database.models import CilentProduct, Product, User
from main.Route.BankCard.forms import Card_Purchase
from main.Route.BankCard.tools import Card_Tools
from main.Route.Products.tools import Product_Tools

cards = Blueprint('cards', __name__)
cilent_service = Cilent_Service()
Db_User = Public_Service(User)
Db_Cilent_Product = Public_Service(CilentProduct)
bank_tools = Card_Tools()
user_service = User_Service()
bank_service = Bank_Service()

@staticmethod
def validate_userbank(current_user):
    user_bank_account=user_service.Get_BankAccount_By_User(current_user)
    if user_bank_account is None:
        flash('You Have No Bank Account , Please Make A New One','danger')
        return True
    return False

@cards.route('/product/purchase', methods=['GET', 'POST'])
@cards.route('/home/product/purchase', methods=['GET', 'POST'])
@login_required
def Purchase():
    
    if validate_userbank(current_user):
        return redirect(url_for('base.HomePage'))
    
    products = cilent_service.Get_All_Cilent_Products_By_User(current_user)
    total_price = 0
    for i in products:
        total_price = total_price + i.product_price
    
    form = Card_Purchase()
    if form.validate_on_submit():
        user_bank = bank_service.Get_Bank_By_Current_User(current_user)
        if bank_tools.Is_Ok_Balance_To_Purchased(user_bank, total_price):
            Db_Cilent_Product.Delete_All(
                cilent_service.Get_All_Cilent_Products_By_User(current_user))
            flash('Your purchase was successful.', 'success')
            return redirect(url_for('cards.Payment_Complete', user_id=user_bank.user.id))
        else:
            flash('Your purchase was unsuccessful. Un Expected Balance ! ', 'danger')
    return render_template('CardTemplate/Card_Purchase.html', form=form)


@cards.route('/products/payment_complete/<int:user_id>')
@cards.route('/home/products/payment_complete/<int:user_id>')
@login_required
def Payment_Complete(user_id):

    user = Db_User.Get_By_Id_Or_404(user_id)

    if validate_userbank(user):
        return redirect(url_for('base.HomePage'))
    
    if user != current_user:
        abort(403)

    user_bank = bank_service.Get_Bank_By_Current_User(user)

    return render_template('CardTemplate/Payment_Complete.html', user=user, user_bank=user_bank)


@cards.route('/remove/preoduct/<int:product_id>')
@cards.route('/home/remove/preoduct/<int:product_id>')
@login_required
def Delete_Cilent_Product(product_id):
    
    product = Db_Cilent_Product.Get_By_Id_Or_404(product_id)
    if product.user != current_user:
        abort(403)
    Db_Cilent_Product.Del_To(product)
    flash('Deleted From Your Directory', 'success')
    return redirect(url_for('base.Cart'))

main/Route/Products/routes.py
from flask import Blueprint, flash, redirect, abort, render_template, request, url_for
from flask_login import current_user, login_required
from main.Core.Db_Core import Public_Service
from main.DataLayer.Core.Cilent_Services import Cilent_Service
from main.DataLayer.Database.models import CilentProduct, Product
from main.Route.Products.forms import Build_New_Product_Form
from main.Route.Products.tools import Product_Tools
from main.Route.Users.tools import User_Tools


products = Blueprint('products', __name__)
Db_Product = Public_Service(Product)
product_tools = Product_Tools()
cilent_service = Cilent_Service()
user_tools = User_Tools()


@products.route('/user/new_purchase/<int:product_id>', methods=['GET', 'POST'])
@products.route('/home/user/new_purchase/<int:product_id>', methods=['GET', 'POST'])
def Sign_New_Purchase(product_id):

    if not (current_user.is_authenticated):
        flash('You are not authenticated. Please login to purchase', 'warning')
        return redirect(url_for('base.HomePage'))

    current_product = Db_Product.Get_By_Id_Or_404(product_id)

    if user_tools.Is_Account_Active(current_product.product_owner):
        flash('Your Account Is Not Active', 'danger')
        return redirect(url_for('base.HomePage'))

    if product_tools.Sign_New_purchase(current_product, current_user):
        flash('Added Your Cart !', 'success')

    return redirect(url_for('base.HomePage'))


@products.route('/user/create_product', methods=['GET', 'POST'])
@products.route('/user/create_product', methods=['GET', 'POST'])
@login_required
def Sign_Product():

    if current_user.role == "USER":
        abort(403)

    form = Build_New_Product_Form()
    if form.validate_on_submit():
        if product_tools.Sign_New_Product(form):
            flash('Your new product has been created successfully', 'success')
            return redirect(url_for('base.HomePage'))
    return render_template('ProductTemplate/Sign_Product.html', form=form)


@products.route('/user/update_product/<int:product_id>', methods=['GET', 'POST'])
@products.route('/user/update_product/<int:product_id>', methods=['GET', 'POST'])
def Update_Product(product_id):

    if current_user.role == "USER":
        abort(403)

    product = Db_Product.Get_By_Id_Or_404(product_id)

    if product.product_owner != current_user:
        abort(403)

    if user_tools.Is_Account_Active(product.product_owner):
        flash('Your Account Is Not Active', 'danger')
        return redirect(url_for('base.HomePage'))

    form = Build_New_Product_Form()
    if form.validate_on_submit():
        product.product_name = form.product_name.data
        product.product_gender = form.product_gender.data
        product.product_price = form.product_price.data
        product.product_summary = form.product_summary.data
        Db_Product.Save_Changes()
        flash('Your Product has been Updated Seccessfully.', 'success')
        return redirect(url_for('base.HomePage'))
    elif request.method == 'GET':
        form.product_name.data = product.product_name
        form.product_gender.data = product.product_gender
        form.product_price.data = product.product_price
        form.product_summary.data = product.product_summary
    return render_template('ProductTemplate/Sign_Product.html', form=form)


@products.route('/user/Delete_Product/<int:product_id>', methods=['GET', 'POST'])
@products.route('/home/user/Delete_Product/<int:product_id>', methods=['GET', 'POST'])
def Delete_Product(product_id):

    if current_user.role == "USER":
        abort(403)

    product = Db_Product.Get_By_Id_Or_404(product_id)

    if product.product_owner != current_user:
        abort(403)

    if user_tools.Is_Account_Active(product.product_owner):
        flash('Your Account Is Not Active', 'danger')
        return redirect(url_for('base.HomePage'))

    Db_Product.Del_To(product)
    flash("Your Product Has been deleted.", 'success')
    return redirect(url_for('base.HomePage'))

main/Route/Users/routes.py
from flask import Blueprint, flash, redirect, abort, render_template, request, url_for
from flask_login import current_user, login_required, logout_user
from main.Core.Db_Core import Public_Service
from main.Core.Security import Email_Token_Security
from main.DataLayer.Core.User_Services import User_Service
from main.DataLayer.Database.models import Card, User
from main.Route.Users.forms import AccountForm, ChangePasswordForm, Confrim_Email_Form, SignInForm, SignUpForm
from main.Route.Users.tools import User_Tools
import redis

users = Blueprint('users', __name__)
user_tools = User_Tools()
user_service = User_Service()
Db = Public_Service(User)
Db_Card = Public_Service(Card)
Sec_Service = Email_Token_Security()


@users.route('/signin', methods=['GET', 'POST'])
@users.route('/home/signin', methods=['GET', 'POST'])
def SignIn():

    if current_user.is_authenticated:
        return redirect(url_for('base.HomePage'))

    form = SignInForm()
    if form.validate_on_submit():
        is_ok = user_tools.Login_User(form)
        if is_ok:
            flash('You Signed in successfully.', 'success')
            return redirect(url_for('base.HomePage'))
        if is_ok is False:
            flash('Your email or your password is incorrect !', 'danger')
    return render_template('UserTemplate/SignIn.html', form=form)


@users.route('/signup', methods=['GET', 'POST'])
@users.route('/home/signup', methods=['GET', 'POST'])
def SignUp():

    if current_user.is_authenticated:
        return redirect(url_for('base.HomePage'))

    form = SignUpForm()
    if form.validate_on_submit():
        user = user_tools.SignUp_User(form=form)
        if user:
            flash('Your Account Was Created Successfully !', 'success')
            return redirect(url_for('users.SignIn'))
        else:
            flash('There Was An Error During Signing Up !', 'danger')
    return render_template('UserTemplate/SignUp.html', form=form)


@users.route('/changepassword', methods=['GET', 'POST'])
@users.route('/home/changepassword', methods=['GET', 'POST'])
@login_required
def ChangePassword():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        if user_tools.Change_UserPassword(form):
            flash('Your Password Was Updated Successfully', 'success')
            return redirect(url_for('base.HomePage'))
        else:
            flash('Your password is not correct !', 'danger')
    return render_template('UserTemplate/ChangePassword.html', form=form)


@users.route('/account', methods=['GET', 'POST'])
@users.route('/home/account', methods=['GET', 'POST'])
@login_required
def Account():
    Cards = user_service.Get_BankCards_By_Current_User(current_user)
    return render_template('UserTemplate/Account.html', Cards=Cards)


@users.route('/account/card/<int:card_id>', methods=['GET', 'POST'])
@users.route('/home/account/card/<int:card_id>', methods=['GET', 'POST'])
@login_required
def Account_Card(card_id):

    card = Db_Card.Get_By_Id_Or_404(card_id)

    if current_user != card.bank_accounts.user:
        abort(403)
    Cards = user_service.Get_BankCards_By_Current_User(current_user)
    # I Did not understand what the fuck is going on here...
    return render_template('UserTemplate/AccountCard.html', card=card, Cards=Cards)
    # Puting This Cards Will Fix All The Errors


@users.route('/change/account', methods=['GET', 'POST'])
@users.route('/home/change/account', methods=['GET', 'POST'])
@login_required
def Change_Account_Info():
    form = AccountForm()
    if form.validate_on_submit():
        current_user.email = form.email.data
        current_user.username = form.username.data
        current_user.phone = "0{}".format(form.phone.data)
        current_user.bio = form.bio.data
        Db.Save_Changes()
        flash('Your account info has been saved.', 'success')
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.phone.data = current_user.phone
        form.bio.data = current_user.bio
    return render_template('UserTemplate/Change_Account_Info.html', form=form)


@users.route('/logout')
@users.route('/home/logout')
@login_required
def Logout():
    logout_user()
    return redirect(url_for('base.HomePage'))


@users.route('/active/email/<int:user_id>', methods=['GET', 'POST'])
@users.route('/home/active/email/<int:user_id>', methods=['GET', 'POST'])
@login_required
def Confrim_Email(user_id):
    # Getting User Or 404
    user = Db.Get_By_Id_Or_404(user_id)

    # Checking For Some DumbAss Works
    if user.user_is_active == 1:
        return redirect(url_for('base.HomePage'))
    # Saving In Redis For Have Only One Message For Send # After 2 Min It Will Be Sended Automaticly
    r = redis.Redis()
    is_sms = r.get('{}_SEND_SMS'.format(user.id))
    is_user = r.get(user.username)
    # Checking For Several Message Sending
    if is_sms != 'YES' and is_user == None and is_user != user.username:
        user_tools.Send_Sms(user)
        r.set(user.username, user.username)
        r.set('{}_SEND_SMS'.format(user.id), 'YES')
    form = Confrim_Email_Form()
    if form.validate_on_submit():
        # Checking Seceret Code For Activition
        if form.confrim_code.data == user.secret_code:
            user.user_is_active = 1
            user.secret_code = Sec_Service.Generate_Random_Secret_Key(
                40000, 60000)
            Db.Save_Changes()
            flash('Your Account Is Acctive Know', 'success')
            # Deleteing Stored Data From Redis
            r.delete('{}_SEND_SMS'.format(user.id))
            r.delete(user.username)
            return redirect(url_for('base.HomePage'))
        else:
            flash('Wronge Verify Code', 'danger')

    return render_template('UserTemplate/Confrim_Email.html', form=form, user=user)


@users.route('/Send/Sms/<int:user_id>')
def Send_SMS(user_id):
    user = Db.Get_By_Id_Or_404(user_id)
    if user.user_is_active == 1:
        return redirect(url_for('base.HomePage'))
    user.secret_code = Sec_Service.Generate_Random_Secret_Key(40000, 60000)
    Db.Save_Changes()
    if user_tools.Send_Sms(user) == False:
        flash('This Is Equal To Zero , Error In Merging The Number')
    flash('You Have 2 Mintues To Enter Your Code OtherWise The Code Will Expire !', 'info')
    return redirect(url_for('users.Confrim_Email', user_id=user_id))

main/templates/BaseTemplate/About_Us.html
{% extends 'layout.html' %}
{% block content %}
<h1 class="text-muted">{{ message }}</h1>
{% endblock content %}

main/templates/BaseTemplate/Cart.html
{% extends 'layout.html' %} {% block content %}
<section class="h-100 h-custom" style="background-color: #d2c9ff">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12">
        <div class="card card-registration card-registration-2" style="border-radius: 15px">
          <div class="card-body p-0">
            <div class="row g-0">
              <div class="col-lg-8">
                <div class="p-5">
                  <div class="d-flex justify-content-between align-items-center mb-5">
                    <h1 class="fw-bold mb-0 text-black">Shopping Cart</h1>
                    <h6 class="mb-0 text-muted">{{ product_lenght }} items</h6>
                  </div>
                  {% for item in products %}
                  <hr class="my-4" />
                  <div class="row mb-4 d-flex justify-content-between align-items-center">
                    <div class="col-md-2 col-lg-2 col-xl-2">
                      <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-shopping-carts/img5.webp"
                        class="img-fluid rounded-3" alt="Cotton T-shirt" />
                    </div>
                    <div class="col-md-3 col-lg-3 col-xl-3">
                      <h6 class="text-muted">{{ item.product_name }}</h6>
                      <h6 class="text-black mb-0">{{ item.product_gender }}</h6>
                    </div>
                    <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                      <button class="btn btn-link px-2"
                        onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                        <i class="fas fa-minus"></i>
                      </button>
                      <button class="btn btn-link px-2"
                        onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                        <i class="fas fa-plus"></i>
                      </button>
                      <a href="{{ url_for('cards.Delete_Cilent_Product',product_id=item.id) }}"
                        class="btn btn-danger btn-sm">Delete</a>
                    </div>
                    <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                      <h6 class="mb-0">{{ item.product_price }}</h6>
                    </div>
                    <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                      <a href="#!" class="text-muted"><i class="fas fa-times"></i></a>
                    </div>
                  </div>
                  {% endfor %}
                  <hr class="my-4" />

                  <div class="pt-5">
                    <h6 class="mb-0">
                      <a href="{{ url_for('base.HomePage') }}" class="text-body"><i
                          class="fas fa-long-arrow-alt-left me-2"></i>Back to
                        shop</a>
                    </h6>
                  </div>
                </div>
              </div>
              <div class="col-lg-4 bg-grey">
                <div class="p-5">
                  <h3 class="fw-bold mb-5 mt-2 pt-1">Summary</h3>
                  <hr class="my-4" />

                  <div class="d-flex justify-content-between mb-4">
                    <h5 class="text-uppercase">{{ product_lenght }} items</h5>
                  </div>

                  <h5 class="text-uppercase mb-3">Shipping</h5>

                  <div class="mb-4 pb-2">
                    <select class="select">
                      <option value="1">Standard-Delivery- €5.00</option>
                      <option value="2">Two</option>
                      <option value="3">Three</option>
                      <option value="4">Four</option>
                    </select>
                  </div>

                  <h5 class="text-uppercase mb-3">Give code</h5>

                  <div class="mb-5">
                    <div class="form-outline">
                      <input type="text" id="form3Examplea2" class="form-control form-control-lg" />
                      <label class="form-label" for="form3Examplea2">Enter your code</label>
                    </div>
                  </div>

                  <hr class="my-4" />

                  <div class="d-flex justify-content-between mb-5">
                    <h5 class="text-uppercase">Total Rounded price</h5>
                    <h5>{{ total_price }}$</h5>
                  </div>
                  {% if products %}
                  <a href="{{ url_for('cards.Purchase') }}" class="btn btn-dark btn-block btn-lg"
                    data-mdb-ripple-color="dark">
                    Purchase
                  </a>
                  {% else %}
                  <a href="{{ url_for('base.HomePage') }}" class="btn btn-dark btn-block btn-lg"
                    data-mdb-ripple-color="dark">
                    Return Back
                  </a>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

main/templates/BaseTemplate/Home.html
{% extends 'layout.html' %} {% block content %}
<div class="content-section">
  {% if current_user.is_authenticated %}
  {% if current_user.user_is_active == 0 %}
  <div class="alert alert-warning">
    Your Account Isn't Activated Yet ! <a href="{{ url_for('users.Change_Account_Info') }}"
      class="btn btn-danger btn-sm">Add Phone</a>
  </div>
  {% endif %}
  <section class="bg-dark py-5 text-light text-center">
    <h1 class="text-warning">
      Take a look our products
      <hr />
      <h6 class="text-light text-center"> Any Items In Each Where You Want ! </h6>
    </h1>
  </section>

  <div class="content-section">
    <section style="background-color: #eee;">
      <div class="container py-5">
        <div class="row justify-content-center g-4">
          {% for item in products %}
          <div class="col-md-8 col-lg-6 col-xl-4">
            <div class="card text-black">
              <i class="fab fa-apple fa-lg pt-3 pb-1 px-3"></i>
              <img src="https://mdbcdn.b-cdn.net/img/Photos/Horizontal/E-commerce/Products/3.webp" class="card-img-top"
                alt="Apple Computer" />
              <div class="card-body">
                <div class="text-center">
                  <h5 class="card-title">Believing is seeing</h5>
                  <p class="text-muted mb-4">{{ item.product_name }}</p>
                </div>
                <div>
                  <div class="d-flex justify-content-between">
                    <span>Name</span><span>{{ item.product_name }}</span>
                  </div>
                  <div class="d-flex justify-content-between">
                    <span>Summary</span><span>{{ item.product_summary }}</span>
                  </div>
                  <div class="d-flex justify-content-between">
                    <span>Gender</span><span>{{ item.product_gender }}</span>
                  </div>
                </div>
                <div class="d-flex justify-content-between total font-weight-bold mt-4">
                  <span>Total</span><span>{{ item.product_price }}$</span>
                </div>

              </div>
              <a href="{{ url_for('products.Sign_New_Purchase',product_id=item.id) }}"
                class="btn btn-secondary btn-sm">Add Your Cart</a>
              {% if item.product_owner.role=="SELLER" and item.product_owner==current_user %}
              <a href="{{ url_for('products.Update_Product',product_id=item.id) }}"
                class="btn btn-primary btn-sm">Update</a>
              <a href="{{ url_for('products.Delete_Product',product_id=item.id) }}"
                class="btn btn-danger btn-sm">Delete</a>
              {% endif %}
            </div>
          </div>

          {% endfor %}
        </div>
      </div>
    </section>
  </div>

  <section class="bg-primary py-5 text-light text-center">
    <div class="container">
      <h4>There is about +1200 sellers and providers </h4>
      <hr>
      <h6 class="text-light">Join Us To Day 1$ per month !</h6>
    </div>
  </section>
  {% else %}
  <div class="alert alert-danger">
    To Continue Browesing Our Site , Please Sign In / Up Now !
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="error-template">
        <h1>
          Oops!</h1>
        <h2>
          404 Not Found</h2>
        <div class="error-details">
          This Is Not A Web Page You Are Looking For !
        </div>
      </div>
    </div>
  </div>
  {% endif %}
</div>
{% endblock content %}