main/Base/routes.py
from flask import Blueprint
from flask import render_template, flash, request, redirect, url_for
from flask_login import current_user, login_required
from main.Base.forms import Search_For_User_Form
import redis

from main.Core.Db_Core import Public_Service
from main.DataLayer.Core.Cilent_Services import Cilent_Service
from main.DataLayer.Core.User_Services import User_Service
from main.DataLayer.Database.models import Product, StaticSite, User

base = Blueprint('base', __name__)
Db_Pu_Product = Public_Service(Product)
Db_Pu_User = Public_Service(User)
user_service = User_Service()
Site_Pu_Service = Public_Service(StaticSite)
cilent_service = Cilent_Service()


@base.route('/')
@base.route('/home')
def HomePage():
    products = Db_Pu_Product.Get_All()
    return render_template('BaseTemplate/Home.html', products=products)


@base.route('/user/cart/', methods=['GET', 'POST'])
@base.route('/home/user/cart', methods=['GET', 'POST'])
@login_required
def Cart():
    user_bank_account = user_service.Get_BankAccount_By_User(current_user)
    if user_bank_account is None:
        flash('You Have No Bank Account , Please Make A New One', 'danger')
        return redirect(url_for('base.HomePage'))

    products = cilent_service.Get_All_Cilent_Products_By_User(current_user)

    product_lenght = len(products)
    total_price = 0
    for i in products:
        total_price = total_price + i.product_price

    return render_template('BaseTemplate/Cart.html', products=products, product_lenght=product_lenght, total_price=int(total_price))


@base.route('/about_us')
@base.route('/home/about_us')
def About_Us():
    r = redis.Redis()
    message = r.get('TEXT')
    flash('{} {}'.format(r.get('SEND_SMS'), r.get('USER')))
    if message is None:
        text = Site_Pu_Service.Get_By_Id(0)
        r.set('TEXT', text.text)
        print('Cathced From Database And Setted For Redis')
    else:
        print('Catched From Redis')
    return render_template('BaseTemplate/About_Us.html', message=message)

main/Route/Users/routes.py
from flask import Blueprint, flash, redirect, abort, render_template, request, url_for
from flask_login import current_user, login_required, logout_user
from main.Core.Db_Core import Public_Service
from main.Core.Security import Email_Token_Security
from main.DataLayer.Core.User_Services import User_Service
from main.DataLayer.Database.models import Card, User
from main.Route.Users.forms import AccountForm, ChangePasswordForm, Confrim_Email_Form, SignInForm, SignUpForm
from main.Route.Users.tools import User_Tools
import redis

users = Blueprint('users', __name__)
user_tools = User_Tools()
user_service = User_Service()
Db = Public_Service(User)
Db_Card = Public_Service(Card)
Sec_Service = Email_Token_Security()


@users.route('/signin', methods=['GET', 'POST'])
@users.route('/home/signin', methods=['GET', 'POST'])
def SignIn():

    if current_user.is_authenticated:
        return redirect(url_for('base.HomePage'))

    form = SignInForm()
    if form.validate_on_submit():
        is_ok = user_tools.Login_User(form)
        if is_ok:
            flash('You Signed in successfully.', 'success')
            return redirect(url_for('base.HomePage'))
        if is_ok is False:
            flash('Your email or your password is incorrect !', 'danger')
    return render_template('UserTemplate/SignIn.html', form=form)


@users.route('/signup', methods=['GET', 'POST'])
@users.route('/home/signup', methods=['GET', 'POST'])
def SignUp():

    if current_user.is_authenticated:
        return redirect(url_for('base.HomePage'))

    form = SignUpForm()
    if form.validate_on_submit():
        user = user_tools.SignUp_User(form=form)
        if user:
            flash('Your Account Was Created Successfully !', 'success')
            return redirect(url_for('users.SignIn'))
        else:
            flash('There Was An Error During Signing Up !', 'danger')
    return render_template('UserTemplate/SignUp.html', form=form)


@users.route('/changepassword', methods=['GET', 'POST'])
@users.route('/home/changepassword', methods=['GET', 'POST'])
@login_required
def ChangePassword():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        if user_tools.Change_UserPassword(form):
            flash('Your Password Was Updated Successfully', 'success')
            return redirect(url_for('base.HomePage'))
        else:
            flash('Your password is not correct !', 'danger')
    return render_template('UserTemplate/ChangePassword.html', form=form)


@users.route('/account', methods=['GET', 'POST'])
@users.route('/home/account', methods=['GET', 'POST'])
@login_required
def Account():
    Cards = user_service.Get_BankCards_By_Current_User(current_user)
    return render_template('UserTemplate/Account.html', Cards=Cards)


@users.route('/account/card/<int:card_id>', methods=['GET', 'POST'])
@users.route('/home/account/card/<int:card_id>', methods=['GET', 'POST'])
@login_required
def Account_Card(card_id):

    card = Db_Card.Get_By_Id_Or_404(card_id)

    if current_user != card.bank_accounts.user:
        abort(403)
    Cards = user_service.Get_BankCards_By_Current_User(current_user)
    # I Did not understand what the fuck is going on here...
    return render_template('UserTemplate/AccountCard.html', card=card, Cards=Cards)
    # Puting This Cards Will Fix All The Errors


@users.route('/change/account', methods=['GET', 'POST'])
@users.route('/home/change/account', methods=['GET', 'POST'])
@login_required
def Change_Account_Info():
    form = AccountForm()
    if form.validate_on_submit():
        current_user.email = form.email.data
        current_user.username = form.username.data
        current_user.phone = "0{}".format(form.phone.data)
        current_user.bio = form.bio.data
        Db.Save_Changes()
        flash('Your account info has been saved.', 'success')
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.phone.data = current_user.phone
        form.bio.data = current_user.bio
    return render_template('UserTemplate/Change_Account_Info.html', form=form)


@users.route('/logout')
@users.route('/home/logout')
@login_required
def Logout():
    logout_user()
    return redirect(url_for('base.HomePage'))


@users.route('/active/email/<int:user_id>', methods=['GET', 'POST'])
@users.route('/home/active/email/<int:user_id>', methods=['GET', 'POST'])
@login_required
def Confrim_Email(user_id):
    # Getting User Or 404
    user = Db.Get_By_Id_Or_404(user_id)

    # Checking For Some DumbAss Works
    if user.user_is_active == 1:
        return redirect(url_for('base.HomePage'))
    # Saving In Redis For Have Only One Message For Send # After 2 Min It Will Be Sended Automaticly
    r = redis.Redis()
    is_sms = r.get('{}_SEND_SMS'.format(user.id))
    is_user = r.get(user.username)
    # Checking For Several Message Sending
    if is_sms != 'YES' and is_user == None and is_user != user.username:
        user_tools.Send_Sms(user)
        r.set(user.username, user.username)
        r.set('{}_SEND_SMS'.format(user.id), 'YES')
    form = Confrim_Email_Form()
    if form.validate_on_submit():
        # Checking Seceret Code For Activition
        if form.confrim_code.data == user.secret_code:
            user.user_is_active = 1
            user.secret_code = Sec_Service.Generate_Random_Secret_Key(
                40000, 60000)
            Db.Save_Changes()
            flash('Your Account Is Acctive Know', 'success')
            # Deleteing Stored Data From Redis
            r.delete('{}_SEND_SMS'.format(user.id))
            r.delete(user.username)
            return redirect(url_for('base.HomePage'))
        else:
            flash('Wronge Verify Code', 'danger')

    return render_template('UserTemplate/Confrim_Email.html', form=form, user=user)


@users.route('/Send/Sms/<int:user_id>')
def Send_SMS(user_id):
    user = Db.Get_By_Id_Or_404(user_id)
    if user.user_is_active == 1:
        return redirect(url_for('base.HomePage'))
    user.secret_code = Sec_Service.Generate_Random_Secret_Key(40000, 60000)
    Db.Save_Changes()
    if user_tools.Send_Sms(user) == False:
        flash('This Is Equal To Zero , Error In Merging The Number')
    flash('You Have 2 Mintues To Enter Your Code OtherWise The Code Will Expire !', 'info')
    return redirect(url_for('users.Confrim_Email', user_id=user_id))

main/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{url_for('base.HomePage')}}">Home</a>
                        </li>
                        {% if current_user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('base.Cart')}}">Cart</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('base.About_Us')}}">About US</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('users.Account')}}">Account</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('users.Logout')}}">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('users.SignUp')}}">Sign Up</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('users.SignIn')}}">Sign In</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('base.About_Us')}}">About US</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        {% with messages=get_flashed_messages(with_categories=True) %}
        {% if messages %}
        {% for category,message in messages %}
        <div class="alert alert-{{ category }}">
            {{message}}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        {% block content %}
        {% endblock content %}
    </div>

    <!-- Footer -->
    <footer class="text-center text-lg-start bg-light text-muted">
        <!-- Section: Social media -->
        <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
            <!-- Left -->
            <div class="me-5 d-none d-lg-block">
                <span>Get connected with us on social networks:</span>
            </div>
            <!-- Left -->

            <!-- Right -->
            <div>
                <a href="" class="me-4 text-reset">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <a href="" class="me-4 text-reset">
                    <i class="fab fa-twitter"></i>
                </a>
                <a href="" class="me-4 text-reset">
                    <i class="fab fa-google"></i>
                </a>
                <a href="" class="me-4 text-reset">
                    <i class="fab fa-instagram"></i>
                </a>
                <a href="" class="me-4 text-reset">
                    <i class="fab fa-linkedin"></i>
                </a>
                <a href="" class="me-4 text-reset">
                    <i class="fab fa-github"></i>
                </a>
            </div>
            <!-- Right -->
        </section>
        <!-- Section: Social media -->

        <!-- Section: Links  -->
        <section class="">
            <div class="container text-center text-md-start mt-5">
                <!-- Grid row -->
                <div class="row mt-3">
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                        <!-- Content -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            <i class="fas fa-gem me-3"></i>Company name
                        </h6>
                        <p>
                            Here you can use rows and columns to organize your footer content. Lorem ipsum
                            dolor sit amet, consectetur adipisicing elit.
                        </p>
                    </div>
                    <!-- Grid column -->

                    <!-- Grid column -->
                    <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Products
                        </h6>
                        <p>
                            <a href="#!" class="text-reset">Angular</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">React</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Vue</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Laravel</a>
                        </p>
                    </div>
                    <!-- Grid column -->

                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Useful links
                        </h6>
                        <p>
                            <a href="#!" class="text-reset">Pricing</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Settings</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Orders</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Help</a>
                        </p>
                    </div>
                    <!-- Grid column -->

                    <!-- Grid column -->
                    <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Contact
                        </h6>
                        <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
                        <p>
                            <i class="fas fa-envelope me-3"></i>
                            info@example.com
                        </p>
                        <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
                        <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
                    </div>
                    <!-- Grid column -->
                </div>
                <!-- Grid row -->
            </div>
        </section>
        <!-- Section: Links  -->

        <!-- Copyright -->
        <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
            © 2021 Copyright:
            <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

</html>